### ISSUE TITLE
Static solver

### ISSUE THREAD

**Issue by Dani-DR** [HeinzBenjamin/FlexCLI#10]
Hi,

is it possible to use Flex Engine to run only N iterations? like the Zombie Kangaroo component?

I want to:
1) apply physics on a mesh,
2) modify the topology of that mesh (adding or removing vertices, edges and faces)
3) and repeat 1 and 2.

My idea would be to run the Flex Engine N times, modify the mesh, and have this process in a loop, for example with Anemone. 

Any way to achieve this? 

Thanks!

**Comment by HeinzBenjamin** [comment]
Hi Dani,

yes that's possible. In the Flex Solver Options component, there's an input called fIter. It lets you define the number of iterations.
Also in the latest FlexHopper version here on Github there are two new components included called telepathy. They let you make loops to easily reuse simulation output as input again
