### ISSUE TITLE
Reset solver freezes my laptop

### ISSUE THREAD

**Issue by DanielAbalde** [HeinzBenjamin/FlexCLI#2]
Hey! I tried this plugin and there is a problem when resetting the solver, at first it took me 5 minutes to respond. Then I did a clean reinstallation of drivers and the reset takes a little less time but still too long! Sounds like incompatibility somewhere, can you help me fix it?

Rhino 5 GH 0.9.0076
Win 10 Home 64bits
Intel Core i5-7200U
Intel(R) HD Graphics 620
NVidia GeForce 940MX
Acer Aspire 5 (A515-51G)

Thank you! I hope I can develop using your library!

**Comment by HeinzBenjamin** [comment]
Hi Daniel,
what are you trying to simulate? A cloth, fluid, rigid bodies? And are you sure, the freeze happens in the engine component and not in the Scene component or Cloth composition component? Those are more prone to freeze....
How many particles do you use and does it help to reduce the number of particles?
Best
Ben

**Comment by DanielAbalde** [comment]
I have had the same problem with sample files and from code when updating the solver. I'd bet it's a problem with the drives, but I'm not sure and I don't know how to fix it.
I could download the proyect and try to debug it or at least locate the error, right? Is there anything I should keep in mind? What would you do?

**Comment by HeinzBenjamin** [comment]
Yes debugging the project would probably be the best. The functions that the engine component performs upon resetting are:
flex.SetParams(params)
flex.SetCollisionGeometry(geom)
flex.SetForceFields(forceFields)
merging scenes a by using:
scene.AppendScene(newScene) to an existing scene-object
and then applying flex.SetScene(scene)
and finally:
flex.SetSolverOptions.

Out of these commands, the things related to scenes (AppendScene, flex.SetScene()) are the heaviest and probably most error prone.
Maybe check if the problem still occurs when you remove all inputs from the Solver component except for the "Scene" component. That'd be my guess.

Also I used Visual Studio 2015 for the project. Getting the dependencies etc. right was quite time-consuming. Let me know if you have major problem getting the debugger to run.
