### ISSUE TITLE
Creating springs with adjustable rest length

### ISSUE THREAD

**Issue by druedan** [HeinzBenjamin/FlexCLI#4]
If I attach a slider to the length input of the spring component, the engine creates a new version of that spring every time I change the slider value while it is running, leaving me with hundreds of slightly-different copies of the spring system when I only want a single system that changes shape. Is this at all possible?

**Comment by HeinzBenjamin** [comment]
Hi,
yes this is by default, to let you add new particles during runtime. There's an input in the FlexHopper engine component called "Lock Mode" that turns this functionality off. Unfortunately this version of FlexHopper doesn't support the spring length being updated during run time. I hope to fix that in one of the future releases. But for now you'll have to reset the simulation to update spring properties.. sorry
Best
Ben

**Comment by HeinzBenjamin** [comment]
Hey druedan,
adaptive spring lengths are now supported from FlexHopper version 1.1.1 and up.
