### ISSUE TITLE
Flexhopper is crashing

### ISSUE THREAD

**Issue by ElkeSP** [HeinzBenjamin/FlexCLI#7]
Hello,
I installed the latest version of flexhopper 1.1.1
But each time when I use an example file e.g. 07_wind_cloth_demo
and I click on the button to start the animation Rhino/ Grasshopper is crashing!

I have Rhino 5 64bit , Windows 10 pro , Nvidia graphic card (but can't install this driver NVIDIA: GeForce Game Ready Driver 372.90 or above)

please see files attached
![capture](https://user-images.githubusercontent.com/41490537/43024762-89809dfe-8c6f-11e8-9f9b-90622e9b224e.JPG)
![capture1](https://user-images.githubusercontent.com/41490537/43024763-899cf21a-8c6f-11e8-8e7f-0c43bec6c822.JPG)
![capture2](https://user-images.githubusercontent.com/41490537/43024765-89bc4fde-8c6f-11e8-887b-baccd69e45e9.JPG)

Thank you very much for your help!
Elke

**Comment by HeinzBenjamin** [comment]
Hi Elke, I'm closing this, I think we figured this out over private message.
The reason for crashes was that the GPU used and the driver were outdated and not supporting NvFlex..
